### PR TITLE
🚀 Add Fiber

### PR DESCRIPTION
**Pull request by Fenny**
<p align="center">
  <a href="https://gofiber.io">
    Fiber
  </a>
<br>
  <a href="https://github.com/gofiber/fiber">Fiber</a> is an <a href="https://github.com/expressjs/express">Express</a> inspired <b>web framework</b> built on top of <a href="https://github.com/valyala/fasthttp">Fasthttp</a>, the <b>fastest</b> HTTP engine for <a href="https://golang.org/doc/">Go</a>. Designed to <b>ease</b> things up for <b>fast</b> development with <b>zero memory allocation</b> and <b>performance</b> in mind.
</p>

```
=== RUN   TestFiber
Running Suite: Fiber Suite
==========================
Random Seed: 1594252703
Will run 1 of 1 specs

2020/07/09 07:58:23 Starting test
2020/07/09 07:58:23 Handler!!
•
Ran 1 of 1 Specs in 0.001 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestFiber (0.00s)
PASS
```

Thanks @sapessi 👍

### CODE REVIEW

**Comment by sapessi** [comment]
Hi @Fenny, apologies for the delay. Can you resolve the conflicts on the mod and sum files then I'll merge.

**Comment by Fenny** [comment]
@sapessi done, thanks 👍

**Comment by JeremyProffitt** [comment]
@sapessi  Any updates on getting this merged in?

**Comment by Prathoss** [comment]
Any news here? Would love to use Fiber on my project.

**Comment by ckcks12** [comment]
@sapessi 👀 hope this be merged in 2020 👍

**Comment by sapessi** [comment]
Merged 🎉 tagging a new release shortly

**Pull request merged**
