### PR TITLE
Add function url support

### PR DESCRIPTION
**Pull request by dza89**
*Description of changes:*

This PR adds function url support for go fiber and http.

### CODE REVIEW

**Comment by suntong** [comment]
How to make use of it please @dza89?

I've forked your PR as my copy -- github.com/suntong/aws-lambda-go-api-proxy

image

```sh
$ grep replace go.mod
replace github.com/awslabs/aws-lambda-go-api-proxy => github.com/suntong/aws-lambda-go-api-proxy v0.0.0-20230922211856-09c9b90f1fd1
```

But for the following code:

```go

// import ...
        fiberadapter "github.com/awslabs/aws-lambda-go-api-proxy/fiber"
//...

// Handler will deal with Fiber working with Lambda
func Handler(ctx context.Context, req events.LambdaFunctionURLRequest) (events.LambdaFunctionURLResponse, error) {
        // If no name is provided in the HTTP request body, throw an error
        return fiberLambda.ProxyFunctionURLWithContext(ctx, req)
}

func main() {
        // Make the handler available for Remote Procedure Call by AWS Lambda
        lambda.Start(Handler)
}
```

I'm getting 
`./main.go:32:21: fiberLambda.ProxyFunctionURLWithContext undefined (type *fiberadapter.FiberLambda has no field or method ProxyFunctionURLWithContext) `

What I've done wrong please? thx

**Comment by dza89** [comment]
@suntong 
Try it with this one: https://github.com/dza89/aws-lambda-go-api-proxy/releases/tag/v0.0.0-test

**Comment by drone-ah** [comment]
Hi,

Thanks for the progress on this! I, however, need gin :wink: Looks simple enough to add in though - so I can probably make the changes tomorrow/Friday. Assuming I am successful, how would you like me to get the changes over to you so you can add it into this PR?

Thanks,

**Comment by dza89** [comment]
If you fork my fork and make a new pr I'll close this one.

**Comment by suntong** [comment]
> If you fork my fork and make a new pr I'll close this one.

Please don't close this one, as I'm still hoping the function url support for go fiber will be adopted by the official code someday, eventually...

**Comment by suntong** [comment]
Oh, I know what you mean, you meant two changes in single PR. Ok. if so, sure.

**Comment by dza89** [comment]
Haha then the post from you under #187  should be under this one?

**Comment by suntong** [comment]
Haha, I re-read my post under #187, and now made it crystal clear what I meant (but won't repeat it under here for I'm afraid beating a dead horse won't gain us anything 🤦🏻‍♂️🤦🏻‍♂️).

**Comment by drone-ah** [comment]
Hi,

I've managed to get it working with gin and have tested it (both with added tests and a test deployed lambda with fURL).

I have opened a PR (#192) with the updates (forked from this branch, so includes all changes from #190 and #187), but am happy to close that down if there is an alternative way to get the changes in.

Thanks again, and please let me know if I can be of any further assistance.

Best Wishes,

**Comment by dza89** [comment]
superseeded by https://github.com/awslabs/aws-lambda-go-api-proxy/pull/192

**Pull request closed without merging**
