### PR TITLE
Support for 2.0 payload format

### PR DESCRIPTION
**Pull request by itmeze**
*Issue #, if available:*
#60 
*Description of changes:*
Adds support for 2.0 payload format.
This is basically a copy of what was done for 1.0 payload format. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by 362228416** [comment]
up

**Comment by 362228416** [comment]
how to use?

**Comment by 362228416** [comment]
Content-Type has a problem，not support text/html.

**Comment by rmanzoku** [comment]
any update?

**Comment by nguyenth91** [comment]
What needs be done to get this PR merged?

**Review by sapessi — APPROVED** [review]

**Pull request merged**
