### PR TITLE
Upgrade github.com/go-chi/chi

### PR DESCRIPTION
**Pull request by vishal24tuniki**
*Issue #, if available:*

*Description of changes:*
Upgrading github.com/go-chi/chi to v5, which is latest and also supports go mod

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by vishal24tuniki** [comment]
cc: @sapessi

**Comment by zhoub** [comment]
🎉

**Comment by zhoub** [comment]
Strongly recommend to merge this PR.

**Comment by vishal24tuniki** [comment]
Hi @sapessi ,could you pls help the this pull req

**Comment by sapessi** [comment]
Going by the size of the change am I correct to assume that there were no breaking changes between versions of Chi?

**Comment by perelman92** [comment]
Can we merge this pr?
I am also waiting for this change.
Thanks

**Comment by vishal24tuniki** [comment]
@sapessi Could you please help with this

**Comment by zhoub** [comment]
It would be great to merge this soon.

**Comment by sapessi** [comment]
tagged 0.11.0

**Pull request merged**
