### PR TITLE
Create a working example for Go Fiber Adapter

### PR DESCRIPTION
**Pull request by bhavik1st**
*Issue #, if available:*
Could not find a working example for Go Fiber Adapter

*Description of changes:*
Created a working example for Go Fiber Adapter

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by efectn — APPROVED** [review]
Lgtm

**Comment by bhavik1st** [comment]
> Lgtm

Thanks for review. 
Travis CI failing the build even prior to this changes. 
Seems previous commit (untested) caused it for some reason.

**Comment by bhavik1st** [comment]
Please merge.

**Comment by drakejin** [comment]
Updating REAMDE.md and creating example are good things! 👍 

Would you check this PR? @ReneWerner87. 

related. https://github.com/awslabs/aws-lambda-go-api-proxy/pull/137.

**Review by ReneWerner87 — APPROVED** [review]

**Comment by bhavik1st** [comment]
Please merge.

cc: @sapessi @drakejin

**Pull request merged**
