### PR TITLE
Infer domain name from request context

### PR DESCRIPTION
**Pull request by RaeesBhatti**
*Issue #, if available:*
Fixes: https://github.com/awslabs/aws-lambda-go-api-proxy/issues/46
Fixes: https://github.com/awslabs/aws-lambda-go-api-proxy/issues/13
*Description of changes:*
`aws-lambda-go` recently [added support for `DomainName` property](https://github.com/aws/aws-lambda-go/releases/tag/v1.17.0) in `RequestContext`. We want to revert to that domain name rather than `aws-serverless-go-api.com`. This change is backwards compatible, in that, people using `GO_API_HOST` env variable can still use that.

I wasn't able to update dependencies properly with `govendor` because it keeps thowing an error when I try to do `govendor get github.com/aws/aws-lambda-go@v1.17.0`:
```
go: finding module for package github.com/aws/aws-lambda-go
can't load package: package github.com/aws/aws-lambda-go: module github.com/aws/aws-lambda-go@latest found (v1.17.0), but does not contain package github.com/aws/aws-lambda-go
Error: exit status 1
```
Please update dependencies manually and publish them here when reviewing this PR!

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RaeesBhatti** [comment]
@sapessi Is this a dead project. Should the community look for other solutions because I don't see any kind of review of feedback?

**Comment by sapessi** [comment]
Apologies @RaeesBhatti, I hadn't looked at this because I saw that the checks failed. Let me take a quick look

**Comment by RaeesBhatti** [comment]
Thank you! The tests are failing because of dependency issues. I couldn't update to `github.com/aws/aws-lambda-go@v1.17.0` because `govendor` kept failing on me for some reason. Please update that dependency and push to this branch and the tests should pass.

**Comment by RaeesBhatti** [comment]
@sapessi I updated `github.com/aws/aws-lambda-go/events`. Can you please take a look again!

**Comment by sapessi** [comment]
Looks like the [build is still failing](https://travis-ci.org/github/awslabs/aws-lambda-go-api-proxy/builds/699942781). I suspect this is because the `go.mod` file is not updated to point to the latest version of the dependency, I only see a change in the sum file.

**Comment by RaeesBhatti** [comment]
@sapessi I've updated the mod file and test. They're passing now. Can you take another look please!

**Pull request merged**
